version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: locator
      POSTGRES_PASSWORD: Aberdeen24
      POSTGRES_DB: postcodetrackerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U locator -d postcodetrackerdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
      # Database configuration
      DB_USER: locator
      DB_PASSWORD: Aberdeen24
      DB_HOST: db
      DB_NAME: postcodetrackerdb
      DATABASE_URL: postgresql://locator:Aberdeen24@db/postcodetrackerdb
      
      # Flask configuration
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-jwt-secret-key-postcode-tracker-2024-consistent}
      
      # Gunicorn configuration (optional overrides)
      WEB_CONCURRENCY: 4
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      - ./logs:/app/logs
    command: gunicorn --config gunicorn.conf.py app:app

volumes:
  postgres_data: